version: '3.9'

services:

  sbm:
    stdin_open: true
    tty: true
    image: dleongsh/speechbertmetrics:1.0.0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ../:/workspace
      - /mnt/d/datasets:/datasets
    ports:
      - 8888:8888
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
    working_dir: /workspace
    command: "jupyter notebook --ip 0.0.0.0 --allow-root"
  