# docker build -t dleongsh/speechbertmetrics:1.0.0 .
FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-runtime

ENV DEBIAN_FRONTEND=noninteractive
# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

RUN apt-get -qq update && \
    apt-get -qq -y install \ 
        git wget build-essential \
        libsndfile1 ffmpeg sox && \
    apt-get -qq autoremove && \
    apt-get -qq clean && \
    rm -rf /var/lib/apt/lists/*

# ADD requirements.txt .
RUN pip install --no-cache-dir --upgrade pip wheel Cython && \
    pip install --no-cache-dir torchaudio==0.13.0 --index-url https://download.pytorch.org/whl/cu116 && \
    pip install --no-cache-dir git+https://github.com/Takaaki-Saeki/DiscreteSpeechMetrics.git && \
    pip install --no-cache-dir notebook && \
    pip cache purge

# ENTRYPOINT ["bash"]
